template = "https://github.com/giellalt/template-lang-und"
rev_id = 326
template_sha = "f8bbffe1f3b8a6dd1aca7238f0aa238554081b55"

[replacements]
__GLOTTOLOG_ID__ = "nort2627"
__REPO__ = "lang-nds"
__UND2C__ = "nds"
__UNDEFINED__ = "Low German"
__UND__ = "nds"
