template = "https://github.com/giellalt/template-lang-und"
rev_id = 285
template_sha = "dc60d9e35b17842271a5a82c114510f9ff1a3d72"

[replacements]
__GLOTTOLOG_ID__ = "nort2627"
__REPO__ = "lang-nds"
__UND2C__ = "nds"
__UNDEFINED__ = "Low German"
__UND__ = "nds"
