template = "https://github.com/giellalt/template-lang-und"
rev_id = 330
template_sha = "ca06c138bb7dc0942a15e60b710a001352e6ebde"

[replacements]
__GLOTTOLOG_ID__ = "nort2627"
__REPO__ = "lang-nds"
__UND2C__ = "nds"
__UNDEFINED__ = "Low German"
__UND__ = "nds"
